{
    "spec": 1,
    "name": "The Binding Of Isaac",
    "previewText": "Isaac and his mother...",
    "main": {
        "ABCGintoNord-ExtraBold": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/Font_soulsV2_Title-Regular.ttf",
        "ggsans-Bold": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/Font_soulsV2_Body-Regular.ttf",
        "ggsans-BoldItalic": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/upheavtt.ttf",
        "ggsans-ExtraBold": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/Font_soulsV2_Title-Regular.ttf",
        "ggsans-ExtraBoldItalic": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/upheavtt.ttf",
        "ggsans-Medium": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/Font_soulsV2_Title-Regular.ttf",
        "ggsans-MediumItalic": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/IsaacFontDescriptionEngRus-Fill.ttf",
        "ggsans-Normal": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/Font_soulsV2_Body-Regular.ttf",
        "ggsans-NormalItalic": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/IsaacFontDescriptionEngRus-Fill.ttf",
        "ggsans-Semibold": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/upheavtt.ttf",
        "ggsans-SemiboldItalic": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/upheavtt.ttf",
        "NotoSans-Bold": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/Font_soulsV2_Body-Regular.ttf",
        "NotoSans-ExtraBold": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/Font_soulsV2_Title-Regular.ttf",
        "NotoSans-Medium": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/Font_soulsV2_Title-Regular.ttf",
        "NotoSans-Normal": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/Font_soulsV2_Body-Regular.ttf",
        "NotoSans-NormalItalic": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/IsaacFontDescriptionEngRus-Fill.ttf",
        "NotoSans-Semibold": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/upheavtt.ttf",
        "SourceCodePro-Semibold": "https://github.com/afk530/The-Saac-Links/raw/refs/heads/main/upheavtt.ttf"
    }
}
